### ISSUE TITLE
Checklist 2020-01 Pré-Deployment 2019

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_app#1]
- [x] Implementar o modo de transporte;
- [x] Ajeitar legenda do indicador de tempo mínimo;
- [x] Adaptar o slider para todos os modos e indicadores;
- [x] Aprimorar o cálculo do ponto de zoom dos mapas: vai ser mesmo pelo centróide do shape? Buscar algo melhor (olhar casos críticos: Manaus e Campo Grande);
- [x] Checar zoom para todas as cidades (depende do item anterior);
- [x] Aprimorar o texto nas caxinhas popups de informação;

**Comment by kauebraga** [comment]
Done.
