### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_app#12]
- [x] Traduzir todas novas infos, especialmente as legendas
- [x] Arredondar valores da legenda de acessibilidade
- [x] Truncar valores p/ variaveis de uso do solo (usar um percentil p/ cada cidade?)
- [x] Ajustar tooltips dos novos mapas
- [x] Ajustar a paleta de cores p; as variaveis de uso do solo / atividades?
- [ ] CMP p/ idade esta todo zerado
- [ ] Atividade para homens e mulheres nao esta na base
- [x] Custom color pallete for income quintiles and deciles
- [x] Translate tooltips

**Comment by kauebraga** [comment]
- [ ] Improve tooltips with info from new indicators/transport modes/activities
